/**
 * YouTube Music identifier policy — pure string rules, no DOM and no network, so
 * both the isolated world and the Node tests can load it. The MAIN world reads the
 * same rules from page-core.js, which Chrome forces to be a separate file.
 *
 * The rules that are specific to this host:
 * - A playable track id is an 11-character video id.
 * - Playlist browse ids arrive prefixed with `VL`; watch endpoints want them bare.
 * - Autogenerated radio and mix lists start with `RD`; a song radio is `RDAMVM<videoId>`.
 * - A video can appear twice in one playlist, so `setVideoId` is the row identity.
 *
 * Anything a second host would spell differently belongs here, not in playback-core.
 */
(function (root, factory) {
  const api = factory();
  root.YTunesYtmIds = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const VIDEO_ID = /^[\w-]{11}$/;
  const RADIO_PREFIX = "RD";
  const SONG_RADIO_PREFIX = "RDAMVM";
  const IDLE_TITLE = /^youtube music$/i;

  function text(value) {
    return String(value ?? "").trim();
  }

  function playable(id) {
    return VIDEO_ID.test(text(id));
  }

  /** Canonical watch-list id: `VLPL123` and `PL123` are the same list. */
  function listId(raw) {
    return text(raw).replace(/^VL/, "");
  }

  /** The list id when it is an autogenerated radio/mix, otherwise "". */
  function radioListId(raw) {
    const list = listId(raw);
    return list.startsWith(RADIO_PREFIX) ? list : "";
  }

  /** A real playlist or album the host can page through, not an endless radio. */
  function isConcreteList(raw) {
    const list = listId(raw);
    return Boolean(list) && !list.startsWith(RADIO_PREFIX);
  }

  /** Song radio for a track, used when there is no concrete list to follow. */
  function radioFor(id) {
    return playable(id) ? `${SONG_RADIO_PREFIX}${text(id)}` : "";
  }

  /** Row identity inside a playlist; distinguishes duplicate videos. */
  function rowKey(track) {
    return text(track?.setVideoId) || text(track?.id) || text(track?.videoId);
  }

  /** True when host chrome shows its own name instead of a track. */
  function idleTitle(title) {
    return IDLE_TITLE.test(text(title));
  }

  return {
    id: "ytm",
    playable,
    listId,
    radioListId,
    isConcreteList,
    radioFor,
    rowKey,
    idleTitle,
  };
});
